version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/your-database
      - JWT_SECRET=your-secret-key
    volumes:
      - ./server:/app
      - /app/node_modules
